[package]
name = "nu-cmdline-parser"
version = "0.0.1"
edition = "2021"

[dependencies]
tree-sitter-nu = { path = "../tree-sitter-nu" }
tree-sitter = "~0.23.0"
clap = { version = "4.5.18", features = ["derive"] }
