[package]
name = "nu-cmdline-parser"
version = "0.0.1"
edition = "2021"

[dependencies]
tree-sitter-nu = { path = "/Users/farseerhe/Workspace/tree-sitter-nu" }
tree-sitter = "~0.24.4"
clap = { version = "4.5.18", features = ["derive"] }
streaming-iterator = "0.1.9"

[features]
debug = []
