# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
exec-on-workspace-change = [ '/bin/sh', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
after-startup-command = [
  'exec-and-forget brew services restart borders',
  'exec-and-forget brew services restart sketchybar',
]

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        30
outer.right =      8

[mode.main.binding]
alt-f = ['mode operation', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=operation']
alt-s = ['mode resize', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=resize']
alt-shift-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=service']

[mode.service.binding]
esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

[mode.operation.binding]
esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
alt-s = ['mode resize', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=resize']

leftSquareBracket = 'focus-monitor prev'
rightSquareBracket = 'focus-monitor next'
shift-leftSquareBracket = ['move-workspace-to-monitor prev', 'focus-monitor prev']
shift-rightSquareBracket = ['move-workspace-to-monitor next', 'focus-monitor next']
h = 'focus --ignore-floating left'
j = 'focus --ignore-floating down'
k = 'focus --ignore-floating up'
l = 'focus --ignore-floating right'

shift-h = ['layout tiling', 'move left']
shift-j = ['layout tiling', 'move down']
shift-k = ['layout tiling', 'move up']
shift-l = ['layout tiling', 'move right']

# # Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
minus = 'join-with left'
equal = 'join-with right'

f = ['layout floating', 'fullscreen on']
space = 'layout tiles horizontal vertical' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

1 = 'workspace 1'
2 = 'workspace 2'
3 = 'workspace 3'
4 = 'workspace 4'
5 = 'workspace 5'

shift-1 = ['move-node-to-workspace 1', 'workspace 1']
shift-2 = ['move-node-to-workspace 2', 'workspace 2']
shift-3 = ['move-node-to-workspace 3', 'workspace 3']
shift-4 = ['move-node-to-workspace 4', 'workspace 4']
shift-5 = ['move-node-to-workspace 5', 'workspace 5']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
alt-f = ['mode operation', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=operation']
enter = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

# [[on-window-detected]]
# if.app-id = 'com.github.wez.wezterm'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-id = 'com.apple.Safari'
# run = 'layout floating'
